### ISSUE TITLE
Navigation between page and image is broken

### ISSUE THREAD

**Issue by gordonklaus** [ExploratoryEngineering/docs.nbiot.engineering#6]
e.g., go to https://docs.nbiot.engineering/tutorials/arduino-serial-forwarder.html
and click on the first image.  The address bar changes but not the content.  Clicking again shows the image.  But clicking the Back button now has no effect (except changing the address).

**Comment by gordonklaus** [comment]
Perhaps unrelated, but I also find that refreshing a page changes the scroll position.

**Comment by pkkummermo** [comment]
This is due to the way Barba.js works. We should make the link `target="_blank"`.

**Comment by pkkummermo** [comment]
Fixed in 2b859817cc6be54f33b5cc2d82cd0ac8ede20443
